author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-08-01
description = Forward-stagewise variable selection estimator
tags = C52
min-version = 2020b
#data-requirement = needs-time-series-data
#gui-main = avgfc_gui
#label = naive forecast(s)
#menu-attachment = MAINWIN/Model/TSModels
public = fsa plot_rho_values plot_coefficient_paths
#menu-only = avgfc_gui
help = fsa_help.txt
sample-script = fsa_sample.inp
depends = string_utils ridge
provider = ridge
