author = Artur Tarassow
email = atecon@posteo.de
version = 0.5
date = 2023-07-12
description = Forward-stagewise boosted regression estimates
tags = C13 C52
min-version = 2020e
public = fsreg print_fsboost_results plot_rho_values plot_coefficient_paths fsreg_gui fsboost_predict
gui-main = fsreg_gui
label = Forward Stagewise
menu-attachment = MAINWIN/Model/LinearModels
help = fsboost.pdf
sample-script = fsboost_sample.inp
depends = string_utils regls
