author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-08-01
description = Forward-stagewise sparse regression estimates
tags = C13 C52
min-version = 2020b
public = fsreg print_fsreg_results plot_rho_values plot_coefficient_paths fsreg_gui
gui-main = fsreg_gui
label = Forward Stagewise
menu-attachment = MAINWIN/Model
help = fsreg_help.txt
sample-script = fsreg_sample.inp
depends = string_utils ridge
provider = ridge
